#!/bin/bash

load inquirer

check() {
  config::load_file $SERVICE_MARIADB_CONFIG

  if [ -z "$SERVICE_MARIADB_HOST" ]; then
    inquirer::text "请输入 SERVICE_MARIADB_HOST:" value
    config::set SERVICE_MARIADB_HOST $value $SERVICE_MARIADB_CONFIG
  fi

  if [ -z "$SERVICE_MARIADB_PORT" ]; then
    inquirer::text "请输入 SERVICE_MARIADB_PORT:" value
    config::set SERVICE_MARIADB_PORT $value $SERVICE_MARIADB_CONFIG
  fi

  if [ -z "$SERVICE_MARIADB_ROOT_PASSWORD" ]; then
    inquirer::text "请输入 SERVICE_MARIADB_ROOT_PASSWORD:" value
    config::set SERVICE_MARIADB_ROOT_PASSWORD $value $SERVICE_MARIADB_CONFIG
  fi

  if [ -z "$SERVICE_MARIADB_USERNAME" ]; then
    inquirer::text "请输入 SERVICE_MARIADB_USERNAME:" value
    config::set SERVICE_MARIADB_USERNAME $value $SERVICE_MARIADB_CONFIG
  fi

  if [ -z "$SERVICE_MARIADB_PASSWORD" ]; then
    inquirer::text "请输入 SERVICE_MARIADB_PASSWORD:" value "$(os::uuid)"
    config::set SERVICE_MARIADB_PASSWORD $value $SERVICE_MARIADB_CONFIG
  fi

  if [ -z "$SERVICE_MARIADB_DATABASE" ]; then
    inquirer::text "请输入 SERVICE_MARIADB_DATABASE:" value
    config::set SERVICE_MARIADB_DATABASE $value $SERVICE_MARIADB_CONFIG
  fi
  
  # @TODO load again
  config::load_file $SERVICE_MARIADB_CONFIG

  # @TODO
  export SERVICE_MARIADB_HOST=$SERVICE_MARIADB_HOST
  export SERVICE_MARIADB_PORT=$SERVICE_MARIADB_PORT
  export SERVICE_MARIADB_ROOT_PASSWORD=$SERVICE_MARIADB_ROOT_PASSWORD
  export SERVICE_MARIADB_USERNAME=$SERVICE_MARIADB_USERNAME
  export SERVICE_MARIADB_PASSWORD=$SERVICE_MARIADB_PASSWORD
  export SERVICE_MARIADB_DATABASE=$SERVICE_MARIADB_DATABASE
}

check $@
