version: '3.7'

services:
  mariadb:
    restart: always
    image: mariadb:${SERVICE_MARIADB_VERSION}
    ports:
      - ${SERVICE_MARIADB_HOST}:${SERVICE_MARIADB_PORT}:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${SERVICE_MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${SERVICE_MARIADB_USERNAME}
      MYSQL_PASSWORD: ${SERVICE_MARIADB_PASSWORD}
      MYSQL_DATABASE: ${SERVICE_MARIADB_DATABASE}
    volumes:
      - ${SERVICE_DATA}:/var/lib/mysql


networks:
  default:
    external: true
    name: compose-ingress
